### PR TITLE
babel support for create-react-app

### PR DESCRIPTION
**Pull request by onurcankaya**
- babel support for applications generated with create-react-app

### CODE REVIEW

**Review by kasperkronborg — COMMENTED** [review]
Looks good.

**Review by kasperkronborg — APPROVED** [review]

**Comment by kasperkronborg** [comment]
I think we should have given @steffenagger a chance to review it also, since he is the original creator of this exact part, but he'll just have to chip in if there is anything that looks out of the ordinary.

**Comment by onurcankaya** [comment]
@kasperkronborg alright, I will keep that in mind next time 😅

**Comment by steffenagger** [comment]
👍

**Pull request merged**
